/*Help texts for the Baby X shell internal commands*/
char help_on_bb[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                 Help on bb                                  *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"bb invokes the BabyBasic interpreter.\n"
"\n"
"BabyBasic used the MiniBasic interpreter by Malolpm McLean as the basis for\n"
"a more powerful scrpting languare to be used in the BABY X shell.\n"
"\n"
"You can get Malcolm\'s book, MiniBasic - how to write a script interpreter.\n"
"\n"
"    The book itself is at https://www.lulu.com/spotlight/bgy1mm\n"
"    And the webpages are at https://malcolmmclean.github.io/minibasic/\n"
"\n"
"BabyBasic is very fluid and constantly being developed, so for rhe latest, go \n"
"to the github site:\n"
"\n"
"    http://malcolmmclean.github.io/babyxrc/\n"
"\n"
"\n";
char help_on_cat[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                 Help on cat                                 *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"cat prints files to standard output, concatenating them.\n"
"\n"
"currently we don\'t support any options.\n";
char help_on_cd[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                 Help on cd                                  *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"cd changes directories.\n"
"\n"
"BBX$ cd poems\n"
"\n"
" will out you in the directory \"poems\"\n"
"\n"
"BBX$ cd ..\n"
"\n"
" will put you in the directory above the one you are currently in.\n"
"\n"
"\n"
"\n";
char help_on_cp[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                 Help on cp                                  *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"cp copies a file to another file.\n"
"\n"
"BBX$ cp <source> <destination>\n"
"\n"
"If destination does not exist, it will attempt to create it.\n";
char help_on_edit[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                Help on edit                                 *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"edit invokes the editor on the file.\n"
"\n"
"$BBX edit <readme.txt>\n"
"\n"
"For technical reasons, it is not possible to include an acceptable text editor\n"
"in the Baby X shell, and so we have to call an external program on the host\n"
"system, Currently this is nano. If you don\'t like nano, or if for some reason\n"
"things don\'t work, try another editor.\n"
"\n"
"babyxfs_shell <filesystem.xml> -editor vi\n"
"\n"
"vi is good editor, widely available, and should work. But you can choose your\n"
"favourite.  ";
char help_on_export[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                               Help on export                                *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"export downloads a file to host system.\n"
"\n"
"BBX$ export <filesystemfile.ext> path/on/host/newfilename.ext\n"
"\n"
"It should usually work. Both text and binary can be exported.";
char help_on_help[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                Help on help                                 *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"To get help, type\n"
"\n"
"BBX$ help\n"
"\n"
"To list the currently available commands, type\n"
"\n"
"BBX$ help -list\n"
"\n"
"To get help on a particular command, type\n"
"\n"
"BBX$ help <command>\n"
"\n";
char help_on_import[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                               Help on import                                *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"import uploads files from the host system to the FileSystem XML file.\n"
"\n"
"BBX$ import <hostfile> myimport.bin\n"
"\n"
"import is a really powerful way of editing a FileSystem XML file.\n"
"\n";
char help_on_ls[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                 Help on ls                                  *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"ls - list files\n"
"\n"
"The Baby X shell has an well featured ls special to it.\n"
"\n"
"It accepts wildcards and options, of which the most useful id -l, or long\n"
"mode. However you can also pass -f to list only files or -d to list only\n"
"directories. Directories have a slash appended to their names, eg\n"
"\n"
"myfolder/\n"
"\n"
"so you can easily recognise them. \n"
"\n"
"You can also specify the sort\n"
"\n"
"BBS$ ls binat/*.bin -sort alpha\n"
"\n"
"                          default - regular sort.\n"
"                          alpha -   alphabetical order sort.\n"
"                          ext -     sort by extension.\n"
"                          size -    sort by size.\n"
"                          none -    don\'t sort.\n";
char help_on_mkdir[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                Help on mkdir                                *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"Creates a directory in the XML file.\n"
"\n"
"BBX$ mkdir <newdirectory>\n"
"\n"
"The directory is of course empty when created.\n"
"\n"
" ";
char help_on_mv[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                 Help on mv                                  *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"mv moves files from one place to another.\n"
"\n"
"BBX$ mv <myfile.txt> <newname.txt>\n"
"\n"
"It will overwrite any old newname.txt.\n"
"\n";
char help_on_rm[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                 Help on rm                                  *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"rm removes files.\n"
"\n"
"BBX$ rm <badfile.ext>\n"
"\n"
"badfile.ext will be permanently deleted. rm does not take wildcards, and you \n"
"can only delete one file at once, as there is currently no recovery system.\n";
char help_on_rmdir[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                                Help on emdir                                *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"rmdir removes directories.\n"
"\n"
"BBX$ rmdir <baddirectory>\n"
"\n"
"It is only possible to remove empty directories, to prevent disasters.\n"
"\n";
char help_on_system[] = "*******************************************************************************\n"
"*                                                                             *\n"
"*                                Baby X shell                                 *\n"
"*                                                                             *\n"
"*                               Help on system                                *\n"
"*                                                                             *\n"
"*******************************************************************************\n"
"\n"
"system invokes a command on the host system.\n"
"\n"
"BBX$ system rm -r *.*\n"
"\n"
"Will run the command \"rm -r *.*\" on the host system.\n"
"\n"
"Baby X accepts no responsibility.\n";
